name: Build CI

on:
  push:
    branches: [ "master" ]

# Jobs section
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: docker.io/kostakoff/rocky-base-images:8-python3.9
    steps:
      - uses: actions/checkout@v4
      - name: python validate pipeline
        shell: bash
        run: |
          ls -la
          python3 ./pipeline/pipeline.py --validate
